stages:
  - test
  - deploy

variables:
  NODE_VERSION: "18"

# Run tests
test:
  stage: test
  image: node:18-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run typecheck
    - npm run lint
  only:
    - merge_requests
    - main

# Deploy to Cloudflare Pages (Staging)
deploy:staging:
  stage: deploy
  image: node:18-alpine
  before_script:
    - npm install -g wrangler
  script:
    - echo "Building Next.js for Cloudflare Pages..."
    - npm ci
    - npm run build
    
    - echo "Deploying to Cloudflare Pages (staging)..."
    - npx wrangler pages deploy .next --project-name=githubplanner --branch=preview
  environment:
    name: staging
    url: https://preview.githubplanner.pages.dev
  only:
    - main
  when: manual

# Deploy to Cloudflare Pages (Production)
deploy:production:
  stage: deploy
  image: node:18-alpine
  before_script:
    - npm install -g wrangler
  script:
    - echo "Building Next.js for Cloudflare Pages..."
    - npm ci
    - npm run build
    
    - echo "Deploying to Cloudflare Pages (production)..."
    - npx wrangler pages deploy .next --project-name=githubplanner --branch=main
  environment:
    name: production
    url: https://githubplanner.pages.dev
  only:
    - tags
  when: manual

