version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    container_name: github-planner-web
    restart: unless-stopped
    environment:
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret-change-in-production}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-default-nextauth-secret-change-in-production}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - EMAIL_FROM=${EMAIL_FROM:-GitHub Planner <noreply@localhost>}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - db_data:/app/data
    networks:
      - github-planner-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  web-dev:
    build:
      context: .
      dockerfile: Containerfile.dev
    container_name: github-planner-web-dev
    restart: unless-stopped
    environment:
      - SQLITE_DB_PATH=/app/data/database.sqlite
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret-for-dev}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-default-nextauth-secret-for-dev}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - EMAIL_FROM=${EMAIL_FROM:-GitHub Planner <dev@localhost>}
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app:Z
      # Persist SQLite database
      - db_data_dev:/app/data
      # Preserve node_modules and build cache in named volumes for performance
      - node_modules_dev:/app/node_modules
      - next_cache_dev:/app/.next
    networks:
      - github-planner-network
    profiles:
      - dev
    command: sh -lc "npm install --legacy-peer-deps && npm run dev"
    # Improve performance for file watching in containers
    security_opt:
      - label=disable
    stdin_open: true
    tty: true

volumes:
  db_data:
    driver: local
  db_data_dev:
    driver: local
  node_modules_dev:
    driver: local
  next_cache_dev:
    driver: local

networks:
  github-planner-network:
    driver: bridge
