name = "ghplanner"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

# For Cloudflare Pages, environment variables should be set in the dashboard:
# Pages → Your Project → Settings → Environment variables
# 
# Required variables:
# - MONGODB_URI
# - NEXTAUTH_SECRET
# - NEXTAUTH_URL
# - GITHUB_ID
# - GITHUB_SECRET
# - EMAIL_SERVER
# - EMAIL_FROM

